FROM mysql:8.0.32

# 添加容器启动时执行SQL
COPY src/main/resources/db/init.sql /docker-entrypoint-initdb.d/init.sql

# 设置terminal进入docker后的默认目录
WORKDIR /usr/bin

# 声明日志数据卷
VOLUME /var/log/mysql
# 声明数据数据卷
VOLUME /var/lib/mysql
# 本地映射配置数据卷
VOLUME /etc/mysql/conf.d

# 暴露端口为3306
EXPOSE 3306

# 设置MySQL root的密码
ENV MYSQL_ROOT_PASSWORD=12345678

# 健康检查
HEALTHCHECK --interval=5s --timeout=3s \
    CMD mysql -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1' 2>/dev/null || exit 1

CMD ["mysqld"]