server:
  port: 8081

spring:
  application:
    name: dubbo-sample-consumer

dubbo:
  application:
    name: dubbo-sample-consumer
    logger: slf4j
    qos-enable: true
    qos-port: 33333
  registry:
    address: ${DUBBO_REGISTRY_ADDRESS:zookeeper://127.0.0.1:2181}
    timeout: 60000   #超时时间设置，太短可能会报错单位是ms，也就是60秒
  metadata-report:
    address: ${DUBBO_METADATA_ADDRESS:zookeeper://127.0.0.1:2181}
    timeout: 60000   #超时时间设置，太短可能会报错单位是ms
  config-center:
    address: ${DUBBO_CONFIG_ADDRESS:zookeeper://127.0.0.1:2181}
  protocol:
    name: dubbo
    port: -1
  consumer:
    group: live
    version: 1.0.0

