spring:
  main:
    banner-mode: off
#  r2dbc:
#    url: r2dbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
#    username: root
#    password: 12345678
  ai:
    mcp:
      server:
        name: mcp-server-webflux
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides weather information tools and resources"
#        base-url: /api/v1
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /sse
#        stdio: true
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true